# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock README.md ./
COPY src ./src

# Install package
RUN pip install --no-cache-dir .

# Expose no ports, listens on stdio
ENTRYPOINT ["sherlock-mcp"]
